<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Log Rogue</AssemblyName>
    <Company>Famecs</Company>
    <Product>로그로그</Product>
	<AssemblyTitle>로그로그</AssemblyTitle>
    <Description>장비 로그 백업 유틸리티</Description>
	<Authors>hwjung</Authors>
    <Copyright>Copyright © 2026 Famecs</Copyright>
    <Version>0.2.0</Version>
	<FileVersion>0.2.0.0</FileVersion>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <ApplicationIcon>LogRogue.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LogRogue.ico" />
	<AssemblyMetadata Include="Developer" Value="hwjung" />
	<AssemblyMetadata Include="Contact" Value="https://github.com/Ro-cks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogRogue.Core\LogRogue.Core.csproj" />
	<Compile Update="Form1.Tray.cs">
		<DependentUpon>Form1.cs</DependentUpon>
	</Compile>
	<Compile Update="Form1.Schedule.cs">
		<DependentUpon>Form1.cs</DependentUpon>
	</Compile>
  </ItemGroup>

</Project>